name: Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 0.1.0

      - name: Output version
        run: echo "Bumped version to ${{ steps.semver.outputs.new_tag }}" 
